<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bayar</name>
   <tag></tag>
   <elementGuidId>8a21133e-81f0-4e07-b3e9-a7a13733f745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.dcd-btn.dcd-btn-primary.mt-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6d9a067-da37-4404-8c4d-cbd75aa64884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>242d877b-7abd-41dc-84ee-11c2b70f90eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcd-btn dcd-btn-primary mt-3</value>
      <webElementGuid>2b1d3302-744c-4397-97a7-b561ee850506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>fbq('track', 'Initial Checkout', {subscriber_id: '655888',product: '1 bulan (30 hari)', currency: 'IDR', value: document.getElementById('price-to-charge').innerHTML.replace(/[^\d.]/g,'')});</value>
      <webElementGuid>74f40e6a-3b9e-4959-bba2-980e220a8ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Bayar
                                </value>
      <webElementGuid>9322463e-0901-4c07-bf44-17172ae0221a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-purchase&quot;)/div[@class=&quot;dcd-rounded-8 border-gray-200 font-weight-500&quot;]/div[@class=&quot;d-flex justify-content-between py-3 px-4&quot;]/div[@class=&quot;text-right&quot;]/button[@class=&quot;dcd-btn dcd-btn-primary mt-3&quot;]</value>
      <webElementGuid>cce62141-2c4e-4556-bc32-cc9e9c25600a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>6f472535-e7e2-4cac-9288-9a490a3ac041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-purchase']/div/div[3]/div[2]/button</value>
      <webElementGuid>f170533c-4670-4a2a-a7c3-4bb4f776d2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1,500,000'])[2]/following::button[1]</value>
      <webElementGuid>b43ac8cb-8866-4e57-97f0-3bb08645fec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Tagihan'])[1]/following::button[1]</value>
      <webElementGuid>df34c0a6-4796-40dd-95ae-a66ee9edca12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar putus. Tak ada kewajiban untuk melanjutkan langganan. Tak ada tagihan rahasia.'])[1]/preceding::button[1]</value>
      <webElementGuid>55d9b082-0ad5-4fa5-ba90-8ae47c5c27b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::button[1]</value>
      <webElementGuid>10df78f0-fe08-4a0d-a04a-4d34d126d467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar']/parent::*</value>
      <webElementGuid>781e96a2-38ff-42dc-aaba-2cfb6ee5f7ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>bf6ace5b-188a-45ad-a051-08c307cc89dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                    Bayar
                                ' or . = '
                                    Bayar
                                ')]</value>
      <webElementGuid>e1fb6fb9-d7e4-4281-bc17-05137f336dc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
