<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>0cc050f2-93e1-4a27-b438-d6053e436abd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dcd-btn.dcd-btn-outline-primary.mr-2.my-sm-0.d-none.d-lg-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d46343e9-541b-4509-928f-09465cfcd1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.dicoding.com/login</value>
      <webElementGuid>09b47042-8a3e-4dd6-9c22-0932954465f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dcd-btn dcd-btn-outline-primary mr-2 my-sm-0 d-none d-lg-block</value>
      <webElementGuid>d6825286-9bf5-4265-af7d-7d87f7af4087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0819152a-ca4d-461f-bcfb-c8fe4ae6771e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#login-modal</value>
      <webElementGuid>a089a9f5-c35b-455e-b6a7-ecd21c471551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>90dde8a5-49cf-450f-a9b9-f1402cbe332c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarSupportedContent&quot;)/div[@class=&quot;navbar-menu-wrapper d-flex align-items-stretch w-100&quot;]/ul[@class=&quot;navbar-nav navbar-nav-right&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;dcd-btn dcd-btn-outline-primary mr-2 my-sm-0 d-none d-lg-block&quot;]</value>
      <webElementGuid>a7bac271-3b4d-461d-8ae4-e1680ff61401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/div/ul/li/a</value>
      <webElementGuid>ad759372-76bb-46ae-b77f-55ac0cc2be24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>d3c0bf6b-5643-4e85-8672-494c2ff9a45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tukarkan point dengan reward menarik.'])[1]/following::a[1]</value>
      <webElementGuid>c83246ab-ca5d-4a61-94a9-120d0f3c8cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ikuti event dan bangun jaringan developer.'])[1]/following::a[2]</value>
      <webElementGuid>85e45a94-0b2d-4e77-8ede-9544a363f8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>e86e6864-fb12-47f0-ba4f-a5aee41c85a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat semua kelas'])[2]/preceding::a[3]</value>
      <webElementGuid>83b01847-c21f-47ae-98f2-b2d26ab5359b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>4c523b70-d2b9-4cfa-a578-2a4ff347580e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.dicoding.com/login')]</value>
      <webElementGuid>7c58198b-e30d-4184-85c1-ec6ba96b85fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a</value>
      <webElementGuid>eeccf6f7-66ed-4102-894b-3225b6a9f604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.dicoding.com/login' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>adc46b86-fe05-4b76-b3b2-76ac302a0cac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
