<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk_login_email</name>
   <tag></tag>
   <elementGuidId>0b43e8da-3450-40fb-84a5-fa3b67ab99f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='login_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;login_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>447d7395-b775-4213-8701-41e77155ba59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control dcd-default-form font-weight-medium auth-form-v3__first-input</value>
      <webElementGuid>0b0080ef-9570-4d57-b8ce-69a379748cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>ea796d35-798b-4425-8326-5edf6e30a15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c21d795b-9af2-4409-ad9d-8a6febfe895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login_email</value>
      <webElementGuid>0718f0c9-c228-4c21-8c8a-0843aedc3c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>416bf00f-364c-42f9-8c71-191f01b8209e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-modal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body p-4&quot;]/form[@class=&quot;auth-form-v3 js-captcha-form&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control dcd-default-form font-weight-medium auth-form-v3__first-input&quot;]</value>
      <webElementGuid>c1d9f951-f998-49f9-8689-fa61b3bbfa8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='login_email']</value>
      <webElementGuid>f06a4e18-77a4-4c89-bdb2-f3e96b7598cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-modal']/div/div/div[2]/form/div/input</value>
      <webElementGuid>e3b0640f-dae4-4784-8dfb-0f773c0829fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e8807a77-f963-4024-afdc-2921cba8b782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Email' and @name = 'login_email' and @type = 'email']</value>
      <webElementGuid>8174e174-8ac6-473a-b6f3-824310f9bae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
